
# coordinator messages
VOTE_REQUEST = 'VOTE_REQUEST'
GLOBAL_COMMIT = 'GLOBAL_COMMIT'
GLOBAL_ABORT = 'GLOBAL_ABORT'

# participant messages
VOTE_COMMIT = 'VOTE_COMMIT'
VOTE_ABORT = 'VOTE_ABORT'
NEED_DECISION = 'NEED_DECISION'

#  coordinator & participant messages
PREPARE_COMMIT = 'PREPARE_COMMIT'
READY_COMMIT = 'READY_COMMIT'
READY_ABORT = 'READY_ABORT'
CRASH = 'CRASH'
ERROR = 'ERROR'
ABORT = 'ABORT'

# participant decisions
LOCAL_ABORT = 'LOCAL_ABORT'
LOCAL_SUCCESS = 'LOCAL_SUCCESS'

# fail-noisy crash timeout
TIMEOUT = 1
